// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_ef_players;

#nullable disable

namespace csharpefplayers.Migrations
{
    [DbContext(typeof(EfPlayersContext))]
    [Migration("20221222153221_Prova")]
    partial class Prova
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("csharp_ef_players.FootballPlayer", b =>
                {
                    b.Property<int>("player_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("player_Id"));

                    b.Property<int>("Team_Id")
                        .HasColumnType("int");

                    b.Property<int>("gameNumber")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("vote")
                        .HasColumnType("float");

                    b.Property<int>("winNumber")
                        .HasColumnType("int");

                    b.HasKey("player_Id");

                    b.HasIndex("Team_Id");

                    b.HasIndex("player_Id");

                    b.ToTable("FootballPlayer");
                });

            modelBuilder.Entity("csharp_ef_players.Team", b =>
                {
                    b.Property<int>("Team_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Team_Id"));

                    b.Property<string>("allenatore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("città")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("colori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Team_Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("csharp_ef_players.FootballPlayer", b =>
                {
                    b.HasOne("csharp_ef_players.Team", "Team")
                        .WithMany("listaGiocatori")
                        .HasForeignKey("Team_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("csharp_ef_players.Team", b =>
                {
                    b.Navigation("listaGiocatori");
                });
#pragma warning restore 612, 618
        }
    }
}
